# this is example of non-blocking

import asyncio
import time


async def brew(name):
    print(f"Brewing {name}....")
    await asyncio.sleep(2)
    # time.sleep(2)
    print(f"{name} is ready...")


async def main():
    await asyncio.gather(brew("Masala Chai"), brew("Ginger Chai"), brew("Elaichi Chai"))


asyncio.run(main=main())


# if we're using await output: (using await its wait for 2 second to run all threads as same time)
# Brewing Masala Chai....
# Brewing Ginger Chai....
# Brewing Elaichi Chai....
# Masala Chai is ready...
# Ginger Chai is ready...
# Elaichi Chai is ready...


# if we're using time.sleep output:
# Brewing Masala Chai....
# Masala Chai is ready...
# Brewing Ginger Chai....
# Ginger Chai is ready...
# Brewing Elaichi Chai....
# Elaichi Chai is ready...
